import re
from pathlib import Path

FONT_HEIGHT = 8
MAX_WIDTH = 8
START_CODE = 0x20
PROJECT_ROOT = Path(__file__).resolve().parents[1]
FONT_SOURCE = PROJECT_ROOT / 'src' / 'font' / 'font6x8_cp1251.h'


def rows_from_source():
    if not FONT_SOURCE.exists():
        raise SystemExit(f"Font source {FONT_SOURCE} not found")

    glyphs = []
    pattern = re.compile(r'0x([0-9A-Fa-f]{2})')
    with FONT_SOURCE.open('r', encoding='utf-8') as handle:
        for line in handle:
            data_part = line.split('}', 1)[0]
            values = [int(match, 16) for match in pattern.findall(data_part)]
            if len(values) == FONT_HEIGHT:
                glyphs.append(values)
    if not glyphs:
        raise SystemExit(f"No glyph rows parsed from {FONT_SOURCE}")
    return glyphs


def cp1251_codepoint(byte_val):
    try:
        char = bytes([byte_val]).decode('cp1251')
    except UnicodeDecodeError:
        return None
    if not char:
        return None
    # Skip unassigned control characters
    if ord(char) < 0x20 and char not in ('\n', '\r', '\t'):
        return None
    return ord(char)


def rows_to_columns(rows):
    columns = []
    min_col = MAX_WIDTH
    max_col = -1
    for col in range(MAX_WIDTH):
        col_bits = 0
        for row_idx, row_val in enumerate(rows):
            if row_val & (1 << (7 - col)):
                col_bits |= 1 << row_idx
        columns.append(col_bits)
        if col_bits:
            if col < min_col:
                min_col = col
            if col > max_col:
                max_col = col

    if max_col >= min_col:
        trimmed = columns[min_col:max_col + 1]
    else:
        # Whitespace glyph: fall back to a narrow blank advance
        trimmed = [0] * 3

    width = len(trimmed)
    if width > MAX_WIDTH:
        trimmed = trimmed[:MAX_WIDTH]
        width = MAX_WIDTH

    trimmed.extend([0] * (MAX_WIDTH - len(trimmed)))
    return width, trimmed


def emit(entries):
    print('// Auto-generated by tools/build_font.py')
    print('#include "ui_font.h"')
    print('static const bareui_font_entry_t bareui_font_data[] = {')
    for codepoint, width, columns in entries:
        col_str = ', '.join(f'0x{value:02X}' for value in columns)
        print(f'    {{0x{codepoint:04X}, {width}, {{{col_str}}}}},')
    print('};')
    print()
    print('#define BAREUI_FONT_ENTRY_COUNT (sizeof(bareui_font_data)/sizeof(bareui_font_data[0]))')


def main():
    glyph_rows = rows_from_source()
    entries = []
    seen = set()
    for offset, rows in enumerate(glyph_rows):
        cp_code = START_CODE + offset
        codepoint = cp1251_codepoint(cp_code)
        if codepoint is None or codepoint in seen:
            continue
        width, columns = rows_to_columns(rows)
        entries.append((codepoint, width, columns))
        seen.add(codepoint)

    if not entries:
        raise SystemExit("No glyph entries generated")

    emit(entries)


if __name__ == '__main__':
    main()
